version: '3.8'

volumes:
  postgres_data: {}

services:
  app:
    build:
      dockerfile: Containerfile
    image: runnerz:latest
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - 8080:8080
    logging:
      options:
        max-size: 10m
      
  
  postgres:
    image: postgres:18.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
